from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

from PIL import Image


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export a named layer from GIMP XCF files into PNG masks."
    )
    parser.add_argument("--xcf-dir", type=Path, required=True, help="Directory containing edited .xcf files.")
    parser.add_argument("--output-dir", type=Path, required=True, help="Directory to write exported mask PNG files.")
    parser.add_argument("--layer-name", default="mask", help="Layer name to export from each XCF.")
    parser.add_argument(
        "--output-suffix",
        default="_mask",
        help="Suffix appended to each XCF stem before .png, for example asset.xcf -> asset_mask.png.",
    )
    parser.add_argument("--gimp-exe", type=Path, help="Optional path to the GIMP executable.")
    parser.add_argument(
        "--binary-threshold",
        type=int,
        default=127,
        help="Grayscale threshold used to convert exported masks into binary 0/255 PNGs.",
    )
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing exported mask PNG files.")
    parser.add_argument("--dry-run", action="store_true", help="Only prepare the export manifest and Scheme script.")
    return parser.parse_args()


def fail(message: str) -> int:
    print(f"error: {message}", file=sys.stderr)
    return 2


def validate_dir(path: Path, label: str) -> Path:
    resolved = path.expanduser().resolve()
    if not resolved.exists():
        raise ValueError(f"{label} does not exist: {resolved}")
    if not resolved.is_dir():
        raise ValueError(f"{label} is not a directory: {resolved}")
    return resolved


def collect_export_jobs(
    xcf_dir: Path,
    output_dir: Path,
    layer_name: str,
    overwrite: bool,
    output_suffix: str,
) -> list[dict[str, object]]:
    xcf_dir = validate_dir(xcf_dir, "xcf dir")
    output_dir = output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    xcf_paths = sorted(path for path in xcf_dir.iterdir() if path.is_file() and path.suffix.lower() == ".xcf")
    if not xcf_paths:
        raise ValueError(f"no .xcf files found in: {xcf_dir}")

    jobs: list[dict[str, object]] = []
    for xcf_path in xcf_paths:
        output_path = output_dir / f"{xcf_path.stem}{output_suffix}.png"
        if output_path.exists() and not overwrite:
            raise ValueError(f"output already exists, pass --overwrite to replace it: {output_path}")
        jobs.append(
            {
                "xcf_name": xcf_path.name,
                "xcf_path": str(xcf_path.resolve()),
                "output_path": str(output_path.resolve()),
                "layer_name": layer_name,
            }
        )
    return jobs


def scheme_quote(text: str) -> str:
    return text.replace("\\", "/").replace("\"", "\\\"")


def build_scheme_content(jobs: list[dict[str, object]], layer_name: str) -> str:
    lines = [
        ";;; Auto-generated by bolt/scripts/export_gimp_xcf_masks.py",
        "",
        "(define (sd-find-layer-by-name image target-name)",
        "  (let* ((layers (gimp-image-get-layers image))",
        "         (count (vector-length layers)))",
        "    (let loop ((i 0))",
        "      (if (>= i count)",
        "          -1",
        "          (let* ((layer (vector-ref layers i))",
        "                 (name (gimp-item-get-name layer)))",
        "            (if (string=? name target-name)",
        "                layer",
        "                (loop (+ i 1))))))))",
        "",
        "(define (sd-build-export-image layer)",
        "  (let* ((width (gimp-drawable-get-width layer))",
        "         (height (gimp-drawable-get-height layer))",
        "         (export-image (gimp-image-new width height RGB))",
        "         (export-layer (gimp-layer-new-from-drawable layer export-image)))",
        "    (gimp-image-insert-layer export-image export-layer 0 0)",
        "    (gimp-item-set-name export-layer \"mask\")",
        "    (gimp-layer-set-mode export-layer 0)",
        "    (gimp-layer-set-opacity export-layer 100.0)",
        "    (gimp-image-set-selected-layers export-image (vector export-layer))",
        "    export-image))",
        "",
        "(define (sd-export-one xcf-path output-path layer-name)",
        "  (script-fu-use-v3)",
        "  (let* ((image (gimp-file-load RUN-NONINTERACTIVE xcf-path))",
        "         (layer (sd-find-layer-by-name image layer-name)))",
        "    (if (equal? layer -1)",
        "        (begin",
        '          (gimp-message (string-append "missing layer: " layer-name " @ " xcf-path))',
        "          (gimp-image-delete image))",
        "        (begin",
        "          (let* ((export-image (sd-build-export-image layer))",
        "                 (export-layer (vector-ref (gimp-image-get-layers export-image) 0)))",
        "            (gimp-file-save RUN-NONINTERACTIVE export-image output-path (vector export-layer))",
        "            (gimp-image-delete export-image))",
        "          (gimp-image-delete image)))))",
        "",
        "(define (sd-export-xcf-mask-batch)",
    ]
    for job in jobs:
        lines.append(
            '  (sd-export-one "{xcf_path}" "{output_path}" "{layer_name}")'.format(
                xcf_path=scheme_quote(str(job["xcf_path"])),
                output_path=scheme_quote(str(job["output_path"])),
                layer_name=scheme_quote(layer_name),
            )
        )
    lines.extend(["  TRUE)", ""])
    return "\n".join(lines)


def write_batch_scheme(output_dir: Path, jobs: list[dict[str, object]], layer_name: str) -> Path:
    scheme_path = output_dir / "export_gimp_xcf_masks.scm"
    scheme_path.write_text(build_scheme_content(jobs=jobs, layer_name=layer_name), encoding="utf-8")
    return scheme_path.resolve()


def write_manifest(output_dir: Path, jobs: list[dict[str, object]]) -> Path:
    manifest_path = output_dir / "gimp_xcf_export_jobs.jsonl"
    manifest_path.write_text(
        "".join(json.dumps(job, ensure_ascii=False) + "\n" for job in jobs),
        encoding="utf-8",
    )
    return manifest_path.resolve()


def resolve_gimp_executable(explicit_path: Path | None = None) -> Path:
    candidates: list[Path] = []
    if explicit_path is not None:
        candidates.append(explicit_path.expanduser())

    for command in (
        "gimp-console-3.2.exe",
        "gimp-console-3.0.exe",
        "gimp-3.2.exe",
        "gimp-3.0.exe",
        "gimp-console.exe",
        "gimp.exe",
    ):
        resolved = shutil.which(command)
        if resolved:
            candidates.append(Path(resolved))

    candidates.extend(
        [
            Path(r"C:\Program Files\GIMP 3\bin\gimp-console-3.2.exe"),
            Path(r"C:\Program Files\GIMP 3\bin\gimp-console-3.0.exe"),
            Path(r"C:\Program Files\GIMP 3\bin\gimp-3.2.exe"),
            Path(r"C:\Program Files\GIMP 2\bin\gimp-console-2.10.exe"),
        ]
    )

    for candidate in candidates:
        resolved = candidate.resolve()
        if resolved.exists() and resolved.is_file():
            return resolved
    raise ValueError("unable to locate GIMP executable, pass --gimp-exe explicitly")


def build_gimp_command(gimp_exe: Path, scheme_path: Path) -> list[str]:
    batch_expr = f'(begin (load "{scheme_quote(str(scheme_path))}") (sd-export-xcf-mask-batch) (gimp-quit 0))'
    return [
        str(gimp_exe),
        "--batch-interpreter=plug-in-script-fu-eval",
        f"--batch={batch_expr}",
    ]


def run_gimp_batch(gimp_exe: Path, scheme_path: Path) -> list[str]:
    command = build_gimp_command(gimp_exe, scheme_path)
    completed = subprocess.run(command, check=False, capture_output=True, text=True)
    if completed.returncode != 0:
        stderr = completed.stderr.strip() or completed.stdout.strip() or "unknown GIMP batch failure"
        raise RuntimeError(stderr)
    return command


def postprocess_exported_masks(export_paths: list[Path], threshold: int) -> None:
    if threshold < 0 or threshold > 255:
        raise ValueError(f"binary threshold must be within [0, 255], got: {threshold}")
    for export_path in export_paths:
        with Image.open(export_path) as image:
            grayscale = image.convert("L")
            binary = grayscale.point(lambda pixel: 255 if pixel > threshold else 0, mode="L")
            binary.save(export_path)


def export_gimp_xcf_masks(args: argparse.Namespace) -> dict[str, object]:
    jobs = collect_export_jobs(
        xcf_dir=args.xcf_dir,
        output_dir=args.output_dir,
        layer_name=args.layer_name,
        overwrite=args.overwrite,
        output_suffix=args.output_suffix,
    )
    output_dir = args.output_dir.expanduser().resolve()
    manifest_path = write_manifest(output_dir, jobs)
    scheme_path = write_batch_scheme(output_dir=output_dir, jobs=jobs, layer_name=args.layer_name)

    summary: dict[str, object] = {
        "mode": "export-gimp-xcf-masks",
        "pair_count": len(jobs),
        "layer_name": args.layer_name,
        "binary_threshold": args.binary_threshold,
        "output_dir": str(output_dir),
        "manifest_path": str(manifest_path),
        "scheme_path": str(scheme_path),
        "output_suffix": args.output_suffix,
    }
    if args.dry_run:
        summary["dry_run"] = True
        summary["gimp_executed"] = False
        return summary

    gimp_exe = resolve_gimp_executable(args.gimp_exe)
    command = run_gimp_batch(gimp_exe, scheme_path)
    postprocess_exported_masks([Path(str(job["output_path"])) for job in jobs], threshold=args.binary_threshold)
    summary["dry_run"] = False
    summary["gimp_executed"] = True
    summary["gimp_exe"] = str(gimp_exe)
    summary["gimp_command"] = command
    return summary


def main() -> int:
    args = parse_args()
    try:
        summary = export_gimp_xcf_masks(args)
    except (OSError, ValueError, RuntimeError) as exc:
        return fail(str(exc))
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
